
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */
public class acceptariProgramari extends javax.swing.JFrame {

    /**
     * Creates new form acceptariProgramari
     */
    public acceptariProgramari() {
        initComponents();
    }
    
    public acceptariProgramari(String email)
    {
        initComponents();
        mail.setText(email);
        Fill();
    }
    
    void Fill()
    {
          Tabel.removeAll();
        DefaultTableModel tblModel=(DefaultTableModel)Tabel.getModel();
        tblModel.setRowCount(0);
        String s="pending";
         try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Select p.data Date,p.email email,p.status stat,p.serviciu serviciu,p.frizer frizer,i.inceput inceput,i.sfarsit sfarsit from programari p,intervale i where i.id=p.nr and p.status=\"pending\" order by p.data";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                String data=rs.getString("Date");
                String email=rs.getString("email");
                String status=rs.getString("stat");
                String serviciu=rs.getString("serviciu");
                String frizer=rs.getString("frizer");
                String inceput=rs.getString("inceput");
                String sfarsit=rs.getString("sfarsit");
                String st=inceput+"-"+sfarsit;
                String prog[]={data,st,frizer,serviciu,email};

                tblModel.addRow(prog);
                
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
             
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schimbStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        statProg = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schimbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schimbStatus.setText("Schimba status");
        schimbStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schimbStatusMouseClicked(evt);
            }
        });
        schimbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schimbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(schimbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 190, 50));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Interval", "Frizer", "Serviciu", "Client"
            }
        ));
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 650, -1));

        statProg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "acceptat", "respins" }));
        getContentPane().add(statProg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 190, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Inapoi");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 180, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Accepta/Refuza programarea");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Accepta programari");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 590, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-01-09 at 21.38.39.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schimbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schimbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schimbStatusActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        meniu_admin f=new meniu_admin(mail.getText());
        f.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void schimbStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schimbStatusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tabel.getModel();
        int selectedR=Tabel.getSelectedRow();
        String Data=model.getValueAt(selectedR, 0).toString();
        String interval=model.getValueAt(selectedR, 1).toString();
        String frizer=model.getValueAt(selectedR, 2).toString();
        String serviciu=model.getValueAt(selectedR, 3).toString();
        String email=model.getValueAt(selectedR, 4).toString();
        String sta=statProg.getSelectedItem().toString();
        String p="";
    
        
        try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Select pret from oferte where oferta='"+ serviciu +"'";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                Integer pret=rs.getInt("pret");
                p=pret.toString();
                
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
      
        
         try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Update programari set status=? where data=? and serviciu=? and frizer=? and email=?";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
                  stmt.setString(1,sta);
                  stmt.setString(2,Data);
                  stmt.setString(3,serviciu);
                  stmt.setString(4,frizer);
                  stmt.setString(5,email);
                  stmt.executeUpdate();
                   JOptionPane.showMessageDialog(this,"Actualizat cu succes");
                   if(sta.equals("acceptat"))
                       SendEmail.sendEmail(email,frizer,serviciu,p,Data,interval);
                   Fill();
                   
                   
                  
 
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_schimbStatusMouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceptariProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceptariProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceptariProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceptariProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceptariProgramari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JButton schimbStatus;
    private javax.swing.JComboBox<String> statProg;
    // End of variables declaration//GEN-END:variables
}
