
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */
public class ActualizareFrizeri extends javax.swing.JFrame {

    /**
     * Creates new form GestionareOferte
     */
    public ActualizareFrizeri() {
        initComponents();
    }
    
     public ActualizareFrizeri(String email) {
        initComponents();
        mail.setText(email);
        Fill();
    }
     
     void Fill()
     {
         Tabel.removeAll();
        DefaultTableModel tblModel=(DefaultTableModel)Tabel.getModel();
        tblModel.setRowCount(0);
         try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Select * from frizer";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                String email=rs.getString("email");
                String parola=rs.getString("parola");
                String nume=rs.getString("nume");
               
                String prog[]={nume,email,parola};

                tblModel.addRow(prog);
                
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        alegere = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Introduceti parola frizerului");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 240, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nume", "Email", "Parola"
            }
        ));
        jScrollPane1.setViewportView(Tabel);
        if (Tabel.getColumnModel().getColumnCount() > 0) {
            Tabel.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 520));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Actualizeaza");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 150, 50));

        alegere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adauga", "sterge" }));
        alegere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegereActionPerformed(evt);
            }
        });
        getContentPane().add(alegere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, -1));

        jButton2.setText("Inapoi");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alegeti optiunea dorita");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, -1));
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Introduceti emailul frizerului");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 240, -1));
        getContentPane().add(nume, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Introduceti numele frizerului");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Actualizeaza frizerii");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 590, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-01-09 at 21.38.39.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Tabel.removeAll();
        String n=nume.getText();
        String p=em.getText();
        String pa=pass.getText();
        
        if(alegere.getSelectedItem().toString().equals("adauga"))
        {
            try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="INSERT into frizer(email,parola,nume)"+" values(?,?,?)";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
             
               
                   stmt.setString(1,p);
                   stmt.setString(2,pa);
                   stmt.setString(3,n);
                   
                  stmt.execute();      
                 stmt.close();
      
                 con.close();
                 
                       
                       Fill();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
            
             try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="INSERT into conturi(email,parola)"+" values(?,?)";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
             
               
                   stmt.setString(1,p);
                   stmt.setString(2,pa);
                   
                   
                  stmt.execute();      
                 stmt.close();
      
                 con.close();
                 
                       JOptionPane.showMessageDialog(this,"Actualizat cu succes");
                       Fill();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
     
     
        }
        else{
            
             try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Delete from frizer where nume='"+ n +"' and email='"+ p +"' and parola='"+ pa +"'";
                  PreparedStatement stmt=con.prepareStatement(sql);

                   
                  stmt.execute();      
                 stmt.close();
      
                 con.close();
                 
                       
                       Fill();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
             
               try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="Delete from conturi where email='"+ p +"' and parola='"+ pa +"'";
                  PreparedStatement stmt=con.prepareStatement(sql);

                   
                  stmt.execute();      
                 stmt.close();
      
                 con.close();
                 
                       JOptionPane.showMessageDialog(this,"Actualizat cu succes");
                       Fill();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
     
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        meniu_admin f=new meniu_admin(mail.getText());
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void alegereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alegereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionareOferte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionareOferte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionareOferte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionareOferte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionareOferte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JComboBox<String> alegere;
    private javax.swing.JTextField em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JTextField nume;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
