import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */
public class Inregistrare extends javax.swing.JFrame {

    /**
     * Creates new form Inregistrare
     */
    public Inregistrare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_inregistrare = new javax.swing.JLabel();
        email_inregistrare = new javax.swing.JLabel();
        casuta_email_inregistrare = new javax.swing.JTextField();
        parola_inregistrare = new javax.swing.JLabel();
        casuta_parola_inregistrare = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buton_inapoi_logare = new javax.swing.JButton();
        fundal_inregistrare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_inregistrare.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        logo_inregistrare.setText("Inregistrare");
        getContentPane().add(logo_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 70));

        email_inregistrare.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        email_inregistrare.setText("Email");
        getContentPane().add(email_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 100, 50));
        getContentPane().add(casuta_email_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 330, 30));

        parola_inregistrare.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        parola_inregistrare.setText("Parola");
        getContentPane().add(parola_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        getContentPane().add(casuta_parola_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 330, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jButton1.setText("Trimite");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 150, 40));

        buton_inapoi_logare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buton_inapoi_logare.setText("inapoi");
        buton_inapoi_logare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_inapoi_logareMouseClicked(evt);
            }
        });
        getContentPane().add(buton_inapoi_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 130, 40));

        fundal_inregistrare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fundal_inregistrare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundal_logare.jpg"))); // NOI18N
        getContentPane().add(fundal_inregistrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -150, 1200, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_inapoi_logareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_inapoi_logareMouseClicked
        // TODO add your handling code here:
        mainframe frame=new mainframe();
        frame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buton_inapoi_logareMouseClicked
public boolean isValidEmail(String email) {
    String regex = "^[a-zA-Z0-9_+&-]+(?:\\.[a-zA-Z0-9_+&-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    Pattern pattern = Pattern.compile(regex);
    if (email == null)
        return false;
    return pattern.matcher(email).matches();
}
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(casuta_email_inregistrare.getText().length()!=0&&casuta_parola_inregistrare.getText().length()!=0 && isValidEmail(casuta_email_inregistrare.getText()))
        {
        
		String email;
		String parola;
		email=casuta_email_inregistrare.getText();
                parola=casuta_parola_inregistrare.getText();
                
            try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql=" INSERT INTO conturi(email,parola)"+" values(?,?)";
                PreparedStatement stmt=con.prepareStatement(sql);
                stmt.setString(1,email);
                stmt.setString(2, parola);
                stmt.execute();
                
                JOptionPane.showMessageDialog(this,"Inregistrat");
                con.close();
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        
        
        
        
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inregistrare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_inapoi_logare;
    private javax.swing.JTextField casuta_email_inregistrare;
    private javax.swing.JTextField casuta_parola_inregistrare;
    private javax.swing.JLabel email_inregistrare;
    private javax.swing.JLabel fundal_inregistrare;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo_inregistrare;
    private javax.swing.JLabel parola_inregistrare;
    // End of variables declaration//GEN-END:variables
}
