/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;
public class logare extends javax.swing.JFrame {

    /**
     * Creates new form logare
     */
    public logare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_logare = new javax.swing.JLabel();
        email_logare = new javax.swing.JLabel();
        parola_logare = new javax.swing.JLabel();
        text_email_logare = new javax.swing.JTextField();
        text_parola_logare = new javax.swing.JTextField();
        buton_trimitere_logare = new javax.swing.JButton();
        buton_inapoi_logare = new javax.swing.JButton();
        fundal_logare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_logare.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        logo_logare.setText("Logare");
        getContentPane().add(logo_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 70));

        email_logare.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        email_logare.setText("email");
        getContentPane().add(email_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 90, 30));

        parola_logare.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        parola_logare.setText("parola");
        getContentPane().add(parola_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 336, 120, 40));
        getContentPane().add(text_email_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 272, 350, 40));
        getContentPane().add(text_parola_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 332, 350, 40));

        buton_trimitere_logare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buton_trimitere_logare.setText("trimitere");
        buton_trimitere_logare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_trimitere_logareMouseClicked(evt);
            }
        });
        getContentPane().add(buton_trimitere_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 130, 40));

        buton_inapoi_logare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buton_inapoi_logare.setText("inapoi");
        buton_inapoi_logare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_inapoi_logareMouseClicked(evt);
            }
        });
        getContentPane().add(buton_inapoi_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 130, 40));

        fundal_logare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundal_inregistrare.jpg"))); // NOI18N
        getContentPane().add(fundal_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_inapoi_logareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_inapoi_logareMouseClicked
            // TODO add your handling code here:
            mainframe frame=new mainframe();
            frame.setVisible(true);
            this.dispose();
            
    }//GEN-LAST:event_buton_inapoi_logareMouseClicked

    private void buton_trimitere_logareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_trimitere_logareMouseClicked
        // TODO add your handling code here:
        
        
        if(text_email_logare.getText().length()!=0&& text_parola_logare.getText().length()!=0)
        {
            	
		String username;
		String password;
		username=text_email_logare.getText();
                password=(text_parola_logare.getText()).toString();
                
                try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="SELECT * FROM conturi where email= '"+ username +"' and parola= '"+ password +"' ";
                PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               if(rs.next())
               {
                  
                   
                        String q="SELECT * FROM admin where username= '"+ username +"' ";
                   
                      PreparedStatement s=con.prepareStatement(q);
                      ResultSet r=s.executeQuery(q);
                      if(r.next())
                      {
                          String email=text_email_logare.getText();
                          meniu_admin frame=new meniu_admin(email);
                          frame.setVisible(true);
                          this.dispose();}
                       
               
                      
                        else
                      {
                          String p="SELECT * FROM frizer where email= '"+ username +"' ";
                          PreparedStatement a=con.prepareStatement(p);
                          ResultSet t=a.executeQuery(p);
                          if(t.next())
                              
                              
                          {   
                              String email=text_email_logare.getText();
                             meniu_frizer frame=new meniu_frizer(email); 
                             frame.setVisible(true);
                             this.dispose();
                          }
                          else
                          {    String email=text_email_logare.getText();
                              meniu_user frame=new meniu_user(email);
                              frame.setVisible(true);
                              this.dispose();
                          }
                          
                          t.close();
                          a.close();
                      }
                      
                     
                
                   
                   
                       r.close();
                      s.close();
               
                
                 rs.close();
      
                 stmt.close();
      
                 con.close();
               }
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
                
                
                

        }
        
    }//GEN-LAST:event_buton_trimitere_logareMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_inapoi_logare;
    private javax.swing.JButton buton_trimitere_logare;
    private javax.swing.JLabel email_logare;
    private javax.swing.JLabel fundal_logare;
    private javax.swing.JLabel logo_logare;
    private javax.swing.JLabel parola_logare;
    private javax.swing.JTextField text_email_logare;
    private javax.swing.JTextField text_parola_logare;
    // End of variables declaration//GEN-END:variables
}
