/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buton_autentificare = new javax.swing.JButton();
        buton_logare = new javax.swing.JButton();
        buton_am_uitat_parola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 200, -1));

        buton_autentificare.setBackground(new java.awt.Color(255, 204, 153));
        buton_autentificare.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        buton_autentificare.setText("Inregistrare");
        buton_autentificare.setToolTipText("");
        buton_autentificare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_autentificareMouseClicked(evt);
            }
        });
        buton_autentificare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_autentificareActionPerformed(evt);
            }
        });
        getContentPane().add(buton_autentificare, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 380, 50));

        buton_logare.setBackground(new java.awt.Color(255, 204, 153));
        buton_logare.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        buton_logare.setText("Logare");
        buton_logare.setToolTipText("");
        buton_logare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_logareMouseClicked(evt);
            }
        });
        getContentPane().add(buton_logare, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 380, 50));

        buton_am_uitat_parola.setBackground(new java.awt.Color(255, 204, 153));
        buton_am_uitat_parola.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        buton_am_uitat_parola.setText("Am uitat parola");
        buton_am_uitat_parola.setToolTipText("");
        buton_am_uitat_parola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_am_uitat_parolaMouseClicked(evt);
            }
        });
        getContentPane().add(buton_am_uitat_parola, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 380, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interior salon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_autentificareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_autentificareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buton_autentificareActionPerformed

    private void buton_autentificareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_autentificareMouseClicked
        // TODO add your handling code here:
        Inregistrare frame=new Inregistrare();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buton_autentificareMouseClicked

    private void buton_logareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_logareMouseClicked
        // TODO add your handling code here:
        logare frame=new logare();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buton_logareMouseClicked

    private void buton_am_uitat_parolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_am_uitat_parolaMouseClicked
        // TODO add your handling code here:
        Uitat f=new Uitat();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buton_am_uitat_parolaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_am_uitat_parola;
    private javax.swing.JButton buton_autentificare;
    private javax.swing.JButton buton_logare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
