
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author coroi
 */
public class meniuProgramari extends javax.swing.JFrame {

    /**
     * Creates new form meniuProgramari
     */
    public meniuProgramari() {
        initComponents();
    }
    public meniuProgramari(String email)
    {
        initComponents();
        mail.setText(email);
        Fill();
        FillOferta();
    }
    
    
    void Fill()
    {
           try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="SELECT nume from frizer";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                   String s=rs.getString("nume");
                   frizeri.addItem(s);
                   
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
             
    }
    
    void FillOferta()
    {
           try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="SELECT oferta,pret from oferte";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                   String s=rs.getString("oferta");
                   Integer p=rs.getInt("pret");
                   
                   serviciu.addItem(s+"-"+p.toString()+" lei");
                   
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        Calendar = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getInterval = new javax.swing.JButton();
        serviciu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        frizeri = new javax.swing.JComboBox<>();
        ore = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inapoi = new javax.swing.JButton();
        trimite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Programari");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 260, 70));
        getContentPane().add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, 190));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Alegeti serviciul dorit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Selectati data dorita");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 146, 260, 40));

        getInterval.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getInterval.setText("Vezi disponibilitatea");
        getInterval.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getInterval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getIntervalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getIntervalMouseEntered(evt);
            }
        });
        getContentPane().add(getInterval, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 180, 40));

        serviciu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviciuMouseClicked(evt);
            }
        });
        getContentPane().add(serviciu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Va rugam selectati frizerul");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 396, 260, 40));

        getContentPane().add(frizeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 210, 40));

        getContentPane().add(ore, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alegeti un interval disponibil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 240, 30));

        inapoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inapoi.setText("Inapoi");
        inapoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inapoiMouseClicked(evt);
            }
        });
        getContentPane().add(inapoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 190, 60));

        trimite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trimite.setText("Trimite");
        trimite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trimiteMouseClicked(evt);
            }
        });
        getContentPane().add(trimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 190, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-01-09 at 21.38.39.jpeg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, new java.awt.Color(102, 102, 102)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 750));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getIntervalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getIntervalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_getIntervalMouseEntered

    private void getIntervalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getIntervalMouseClicked
        // TODO add your handling code here:
        ore.removeAllItems();
        String f=frizeri.getSelectedItem().toString();
        var date1 = Calendar.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = sdf.format(date1);
          try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="SELECT id, inceput, sfarsit FROM intervale WHERE id NOT IN (SELECT nr FROM programari where frizer='"+ f +"' and data='"+ dateString +"')";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
               ResultSet rs=stmt.executeQuery(sql);
               while(rs.next())
               {
                    String inceput=rs.getString("inceput");
                String sfarsit=rs.getString("sfarsit");
                Integer nr=rs.getInt("id");
                String st=nr.toString()+")"+inceput+"-"+sfarsit;
                ore.addItem(st);
                      
                    
               }
               
                   rs.close();
      
                 stmt.close();
      
                 con.close();
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
             
        
    }//GEN-LAST:event_getIntervalMouseClicked

    private void serviciuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviciuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_serviciuMouseClicked

    private void trimiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trimiteMouseClicked
     String frizer=frizeri.getSelectedItem().toString();   
     String em=mail.getText();
     String y=(ore.getSelectedItem()).toString();
     String ids=y.split("\\)")[0];
     Integer id=Integer.parseInt(ids);
     String x=serviciu.getSelectedItem().toString();
     String oferta=x.split("-")[0];
     
     String p=x.split("-")[1];
     String pr=p.split(" ")[0];
     Integer pret=Integer.parseInt(pr);
            var date = Calendar.getDate();
SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
String dateString = sdf.format(date);
     
     
     try
         {
             Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/heaven","root","");
                String sql="INSERT into programari(email,data,status,serviciu,frizer,nr)"+" values(?,?,?,?,?,?)";
                  PreparedStatement stmt=con.prepareStatement(sql);
                
             
               
                   stmt.setString(1,em);
                   stmt.setString(2,dateString);
                   stmt.setString(3, "pending");
                   stmt.setString(4,oferta);
                   stmt.setString(5, frizer);
                   stmt.setInt(6,id);
                   stmt.execute();      
                 stmt.close();
      
                 con.close();
                 
                       JOptionPane.showMessageDialog(this,"Solicitarea dumneavoastra a fost trimisa");
                 
             
         }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
     
        
    }//GEN-LAST:event_trimiteMouseClicked

    private void inapoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inapoiMouseClicked
        // TODO add your handling code here:
        meniu_user f = new meniu_user(mail.getText());
        f.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_inapoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meniuProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meniuProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meniuProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meniuProgramari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meniuProgramari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JComboBox<String> frizeri;
    private javax.swing.JButton getInterval;
    private javax.swing.JButton inapoi;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mail;
    private javax.swing.JComboBox<String> ore;
    private javax.swing.JComboBox<String> serviciu;
    private javax.swing.JButton trimite;
    // End of variables declaration//GEN-END:variables
}
